# Generated by Django 5.2.1 on 2025-05-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_count', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('SINGLE_ROOM', 'Одна комната (студия)'), ('ONE_BEDROOM', 'Одна комната с отдельной спальней'), ('TWO_BEDROOM', 'Две комнаты с общей ванной'), ('TWO_BEDROOM_ENSUITE', 'Две комнаты с отдельными ванными'), ('THREE_BEDROOM', 'Три комнаты'), ('SUITE', 'Сьют / Апартаменты'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('PRIVATE_ROOM_IN_SHARED', 'Отдельная комната в общей квартире'), ('LOFT', 'Лофт / Мансарда'), ('STUDIO', 'Студия')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
